### ISSUE TITLE
storybook 테스팅을 위한 다크모드 구현 방식 변경

### ISSUE THREAD

**Issue by bel1c10ud** [prgrms-fe-devcourse/FEDC5_brewers_hyunju#18]
> `storybook`에서 다크모드 디자인 확인을 원활하게 하기 위해 아래 작업을 진행하려고 합니다.
>
> 1. 다크모드 구현 방식 변경
> 2. `storybook` 애드온 적용
>
> 현재 `storybook` 애드온 적용 방식이 두 가지가 있습니다. 
> 아래 스크린샷 보시고 어떤 방식이 좋을지 의견 주시면 감사하겠습니다.

## :rocket: 구현 기능
- [window.matchMedia](https://developer.mozilla.org/ko/docs/Web/API/Window/matchMedia)를 이용하여 OS의 다크모드 상태에 따라 `html` 태그에 `.dark` 클래스 토글
- CSS 전역 색상 변수 분기 기준을 기존 `prefers-color-scheme: dark`에서 `.dark` 클래스로 변경
- `storybook`상에서 `toolbar`의 버튼으로 다크모드를 테스트 할 수 있도록 애드온 설정

## :pushpin: 스크린샷
> 기존 다크모드의 불편함

![image1](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86952779/4e6d7088-72bb-44d0-857f-ec668b39b127)

> 1번 방식 (전체 다크모드)

![chrome_LBWcP9SLrk](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86952779/21068a72-ff69-4720-af40-e946cc4bd497)

> 2번 방식 (Preview 부분만 다크모드)

![chrome_f0OMHojZwB](https://github.com/prgrms-fe-devcourse/FEDC5_brewers_hyunju/assets/86952779/a90e10e1-0e8f-42d2-b9e2-f2db9fdb9fd3)

## :page_facing_up: 작업 내용
- [x] [window.matchMedia](https://developer.mozilla.org/ko/docs/Web/API/Window/matchMedia)를 이용하여 OS의 다크모드 상태에 따라 `html` 태그에 `.dark` 클래스 토글
- [x] CSS 전역 색상 변수 분기 기준을 기존 `prefers-color-scheme: dark`에서 `.dark` 클래스로 변경
- [x] `storybook`상에서 `toolbar`의 버튼으로 다크모드를 테스트 할 수 있도록 애드온 설정

**Comment by yjc2021** [comment]
2번 방식이 더 좋은 것 같습니다 :)

**Comment by nnahyunn** [comment]
1번 방식이 더 좋은 것 같습니다😊

**Comment by yeon-kk** [comment]
1번이요 😄

**Comment by jiheeshin27** [comment]
1번이 좋은 것 같습니다!
