### ISSUE TITLE
폰트

### ISSUE THREAD

**Issue by bel1c10ud** [prgrms-fe-devcourse/FEDC5_brewers_hyunju#42]
## :rocket: 구현 기능
프로젝트에서 사용할 폰트를 결정합니다.

## :pushpin: 목록

> 목록을 보시고 자유롭게 의견 주세요
> 추가로 논의하고 싶은 폰트 남겨주시면 목록에 추가하도록 하겠습니다.

- [x] [SUIT](https://sun.fo/suit)
- [ ] [Pretendard](https://github.com/orioncactus/pretendard)

## :page_facing_up: 작업 내용
- [x] 사용할 폰트 결정
- [ ] 결정된 폰트 설정

**Comment by yjc2021** [comment]
SUIT이 좋아보입니다!

**Comment by jiheeshin27** [comment]
저는 Pretendard 에 한 표 입니다.

**Comment by yeon-kk** [comment]
앗 구경하다가 늦었습니다! Pretendard 요~! 👍
